/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisModule: typeof import('./src/components/Analysis/AnalysisModule.vue')['default']
    MapCharts: typeof import('./src/components/Charts/MapCharts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoCharts: typeof import('./src/components/Charts/VideoCharts.vue')['default']
    VideoForm: typeof import('./src/components/Table/VideoForm.vue')['default']
    VideoForWebRTC: typeof import('./src/components/Video/VideoForWebRTC.vue')['default']
    VideoForWS: typeof import('./src/components/Analysis/VideoForWS.vue')['default']
    VideoList: typeof import('./src/components/Analysis/VideoList.vue')['default']
    VideoModule: typeof import('./src/components/Video/VideoModule.vue')['default']
  }
}
