/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsCategoryChart: typeof import('./src/components/Charts/ActionsCategoryChart/ActionsCategoryChart.vue')['default']
    ActionsListForm: typeof import('./src/components/Charts/ActionsListForm/ActionsListForm.vue')['default']
    ActionsTendency: typeof import('./src/components/Charts/ActionsTendency/ActionsTendency.vue')['default']
    AnalysisModule: typeof import('./src/components/Analysis/AnalysisModule.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    BasicCard: typeof import('./src/components/BasicCard.vue')['default']
    CustomScrollBoard: typeof import('./src/components/Charts/CustomScrollBoard/CustomScrollBoard.vue')['default']
    MapCharts: typeof import('./src/components/Charts/MapCharts.vue')['default']
    OnEnter: typeof import('./src/components/Ani/OnEnter.vue')['default']
    OnHover: typeof import('./src/components/Ani/OnHover.vue')['default']
    PointCharts: typeof import('./src/components/Body/PointCharts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenLoading: typeof import('./src/components/Loading/ScreenLoading.vue')['default']
    Title: typeof import('./src/components/TopBar/Title.vue')['default']
    TotalCharts: typeof import('./src/components/Body/TotalCharts.vue')['default']
    TotalTendency: typeof import('./src/components/Charts/TotalTendency/TotalTendency.vue')['default']
    VideoCharts: typeof import('./src/components/Charts/VideoCharts.vue')['default']
    VideoForm: typeof import('./src/components/Table/VideoForm.vue')['default']
    VideoForWebRTC: typeof import('./src/components/Video/VideoForWebRTC.vue')['default']
    VideoForWS: typeof import('./src/components/Analysis/VideoForWS.vue')['default']
    VideoInfo: typeof import('./src/components/Body/VideoInfo.vue')['default']
    VideoList: typeof import('./src/components/Analysis/VideoList.vue')['default']
    VideoModule: typeof import('./src/components/Video/VideoModule.vue')['default']
  }
}
