// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAction = "actions"

// Action mapped from table <actions>
type Action struct {
	ActionID   int64  `gorm:"column:actionId;primaryKey;autoIncrement:true" json:"actionId"`
	ActionName string `gorm:"column:actionName;not null" json:"actionName"`
}

// TableName Action's table name
func (*Action) TableName() string {
	return TableNameAction
}
