// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCar = "cars"

// Car mapped from table <cars>
type Car struct {
	CarID string `gorm:"column:carId;primaryKey" json:"carId"`
}

// TableName Car's table name
func (*Car) TableName() string {
	return TableNameCar
}
