// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStream = "streams"

// Stream mapped from table <streams>
type Stream struct {
	StreamID   int32   `gorm:"column:streamId;primaryKey;autoIncrement:true" json:"streamId"`
	StreamName string  `gorm:"column:streamName;not null" json:"streamName"`
	Addr       string  `gorm:"column:addr" json:"addr"`
	Latitude   float64 `gorm:"column:latitude;not null;default:-1" json:"latitude"`
	Longitude  float64 `gorm:"column:longitude;not null;default:-1" json:"longitude"`
}

// TableName Stream's table name
func (*Stream) TableName() string {
	return TableNameStream
}
