# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yolo.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'yolo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nyolo.proto\"J\n\x0cImageRequest\x12\n\n\x02id\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x12\r\n\x05index\x18\x03 \x01(\x03\"1\n\x0f\x44\x65tectionResult\x12\x1e\n\ndetections\x18\x01 \x03(\x0b\x32\n.Detection\"]\n\tDetection\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\t\x12\x1a\n\x04\x62\x62ox\x18\x02 \x01(\x0b\x32\x0c.BoundingBox\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x10\n\x08\x62\x65havior\x18\x03 \x01(\x05\"P\n\x0b\x42oundingBox\x12\x10\n\x08x_center\x18\x01 \x01(\x02\x12\x10\n\x08y_center\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x32@\n\x0bYoloService\x12\x31\n\x0c\x44\x65tectSingle\x12\r.ImageRequest\x1a\x10.DetectionResult\"\x00\x42\nZ\x08.;yolov8b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010.;yolov8'
  _globals['_IMAGEREQUEST']._serialized_start=14
  _globals['_IMAGEREQUEST']._serialized_end=88
  _globals['_DETECTIONRESULT']._serialized_start=90
  _globals['_DETECTIONRESULT']._serialized_end=139
  _globals['_DETECTION']._serialized_start=141
  _globals['_DETECTION']._serialized_end=234
  _globals['_BOUNDINGBOX']._serialized_start=236
  _globals['_BOUNDINGBOX']._serialized_end=316
  _globals['_YOLOSERVICE']._serialized_start=318
  _globals['_YOLOSERVICE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
