// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRecord = "records"

// Record mapped from table <records>
type Record struct {
	RecordID int64  `gorm:"column:recordId;primaryKey;autoIncrement:true" json:"recordId"`
	CarID    string `gorm:"column:carId;not null" json:"carId"`
	StreamID int32  `gorm:"column:streamId;not null" json:"streamId"`
	ActionID int64  `gorm:"column:actionId" json:"actionId"`
	Time     int64  `gorm:"column:time;not null" json:"time"`
}

// TableName Record's table name
func (*Record) TableName() string {
	return TableNameRecord
}
